Replace deprecated in GTK 4.20 call to Texture::from_pixbuf() with Texture::from_bytes(). Fix CI.
Deprecation cause CI failure with the following error:

    error: use of deprecated associated function `relm4::gtk4::gdk4::Texture::for_pixbuf`: Since 4.20
      --> relm4/examples/embedded_logo.rs:20:14
       |
    20 |     Texture::for_pixbuf(&pixbuf)
       |              ^^^^^^^^^^
       |
       = note: `-D deprecated` implied by `-D warnings`
       = help: to override `-D warnings` add `#[allow(deprecated)]`

    error: could not compile `relm4` (example "embedded_logo") due to 1 previous error
    warning: build failed, waiting for other jobs to finish...
    Error: Process completed with exit code 101.

Links:
- https://gtk-rs.org/gtk4-rs/stable/latest/docs/gdk4/struct.Texture.html#deprecated-since-420
- https://gtk-rs.org/gtk4-rs/stable/latest/docs/gdk4/struct.Texture.html#method.from_bytes
- https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2879