Set "--cfg docsrs" on RUSTDOCFLAGS instead of RUSTFLAGS. This fixes "docs" job in CI.
I'm not sure why "--cfg docsrs" was set in RUSTFLAGS environment
variable, but it leads to failures as the following:

    RUSTDOCFLAGS="-D warnings" RUSTFLAGS="--cfg docsrs" cargo +nightly-2025-09-27 doc --all-features

    error[E0412]: cannot find type `PhantomData` in module `_serde::__private228`
      --> /home/zekefast/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zvariant-5.8.0/src/file_path.rs:36:58
       |
    36 | #[derive(Type, Debug, Default, PartialEq, Eq, Serialize, Deserialize, Clone, Ord, PartialOrd)]
       |                                                          ^^^^^^^^^^^ not found in `_serde::__private228`
       |
       = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)
    help: consider importing this struct
       |
     1 + use std::marker::PhantomData;
       |

    error[E0412]: cannot find type `Formatter` in module `_serde::__private228`
      --> /home/zekefast/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/zvariant-5.8.0/src/file_path.rs:36:58
       |
    36 | #[derive(Type, Debug, Default, PartialEq, Eq, Serialize, Deserialize, Clone, Ord, PartialOrd)]
       |                                                          ^^^^^^^^^^^ not found in `_serde::__private228`
       |
       = note: this error originates in the derive macro `Deserialize` (in Nightly builds, run with -Z macro-backtrace for more info)
    help: consider importing this struct
       |
     1 + use std::fmt::Formatter;
       |

The failure occurs on "icons" example compilation and likely caused by
differences in flags provided during compilation and macro expantion
(but I am not 100% sure about that).

I tried many different combinations of setting exact versions of serde
and serde_derive with feature flags and converting dependencies to
workspace dependencies, but nothing works, except of moving "--cfg
docsrs" to RUSTDOCFLAGS.

Most other projects, like .e.g. tokio use RUSTDOCFLAGS for that. So, I
may assume that would be more correct way to set docsrs.

References:
- https://users.rust-lang.org/t/how-to-document-optional-features-in-api-docs/64577
- https://users.rust-lang.org/t/tokio-rustflags-cfg-docsrs-trouble/112683
- https://github.com/winnow-rs/winnow/issues/835#issuecomment-3439794153